version: '3.8'

# Docker-Compose 方式启动容器的 YAML 配置文件
# 当前配置仅保证可以启动容器；更多配置参数请参考镜像 README.md 文档中说明
services:
  openldap:
    image: 'registry.cn-shenzhen.aliyuncs.com/colovu/docker-openldap'
    ports:
      - '389:8389'
    volumes:
      - 'app_conf:/srv/conf'
    environment:
      - ENV_DEBUG=yes

# 定义本地数据卷，由系统管理，需要手动删除
volumes:
  app_conf:
    driver: local
  app_data:
    driver: local
  var_log:
    driver: local
